### ISSUE TITLE
TypeError: plugin.apply is not a function

### ISSUE THREAD

**Issue by rhinenoir** [tylingsoft/markdown-it-mermaid#4]
https://github.com/valeriangalliat/markdown-it-anchor/issues/12

不管在hexo还是Ghost用都会遇到TypeError: plugin.apply is not a function

请问如何解决呢？

**Comment by noisygerman** [comment]
Work around, if you don't use babel/ES6

```javascript
const md = require( 'markdown-it' )();
md.use( require( 'markdown-it-mermaid' ).default );

```

**Comment by rhinenoir** [comment]
@noisygerman yeah, I've worked it out through the same way, thx too

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nehalbhagat** [comment]
@noisygerman  any inputs on when can a fix for this issue be pushed ?

**Comment by tylerlong** [comment]
```json
"main": "dist/index.js",
```

`dist/index.js` is precompiled with babel:

```
module.exports=function(e){function r(n){if(t[n])return t[n].exports;var a=t[n]={i:n,l:!1,exports:{}};return e[n].call(a.exports,a,a.exports,r),a.l=!0,a.exports}var t={};return r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{configurable:!1,enumerable:!0,get:n})},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},r.p="",r(r.s=0)}([function(e,r,t){"use strict";Object.defineProperty(r,"__esModule",{value:!0});var n=t(1),a=function(e){return e&&e.__esModule?e:{default:e}}(n),u=function(e){try{return a.default.parse(e),'<div class="mermaid">'+e+"</div>"}catch(e){var r=e.str;e.hash;return"<pre>"+r+"</pre>"}},i=function(e){e.mermaid=a.default,a.default.loadPreferences=function(e){var r=e.get("mermaid-theme");void 0===r&&(r="default");var t=e.get("gantt-axis-format");return void 0===t&&(t="%Y-%m-%d"),a.default.initialize({theme:r,gantt:{axisFormatter:[[t,function(e){return 1===e.getDay()}]]}}),{"mermaid-theme":r,"gantt-axis-format":t}};var r=e.renderer.rules.fence.bind(e.renderer.rules);e.renderer.rules.fence=function(e,t,n,a,i){var o=e[t],f=o.content.trim();if("mermaid"===o.info)return u(f);var c=f.split(/\n/)[0].trim();return"gantt"===c||"sequenceDiagram"===c||c.match(/^graph (?:TB|BT|RL|LR|TD);?$/)?u(f):r(e,t,n,a,i)}};r.default=i},function(e,r){e.exports=require("mermaid")}]);
```

I've no idea why you have this ES6 issue.

**Comment by tylerlong** [comment]
And by the way I don't think append `.default` to the code is an issue. It's just the difference between ES5 module and ES6 module I think. I will close it for now.

**Comment by toddpi314** [comment]
To make this clearer at the API level:
- Consider building with [babel-plugin-add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports)
- Consider adding guidance on the `.default` path in the README for the project

FYI, vuepress is shipping on Markdown-it and doesn't use ES6; your probably going to have a few people hit this on that path of adoption. 

Thanks!

**Comment by neumayr** [comment]
Hi @tylerlong 👋 – would you consider implement the suggested changes from https://github.com/tylingsoft/markdown-it-mermaid/issues/4#issuecomment-388853689? 🙄

People trying to use mermaid with [vuepress](https://vuepress.vuejs.org/) and having trouble using `markdown-it-mermaid` out-of-the-box. 

💬 Thread: https://github.com/vuejs/vuepress/issues/111

**Comment by busyhe** [comment]
@neumayr me too, use vuepress
