### ISSUE TITLE
does the mermaid dependency lock mermaid version to 7.x?

### ISSUE THREAD

**Issue by tessus** [tylingsoft/markdown-it-mermaid#6]
Mermaid is at version `8.0.0`, but your dependency file states `^7.1.2`. What does that mean exactly?
Does it mean that even though I use 8.0.0 in my project and if I also used your plugin, your plugin would use mermaid `7.x` instead?

**Comment by tessus** [comment]
Additional info: I think I can't use this plugin in [Joplin](https://github.com/laurent22/joplin) anyway (I wanted to add mermaid support). Something is not working. Maybe something is still missing, or I have to create additional rules. I have to check with the dev of Joplin.

Unless you want to try adding Mermaid support to [Joplin](https://github.com/laurent22/joplin), we can close this ticket.  I'll leave it open for another 2 days and then close it.

**Comment by smarthug** [comment]
try this one
https://github.com/liradb2000/markdown-it-mermaid

we had version issue and we fixed some issues

**Comment by tessus** [comment]
@Zzing-gu thanks for the link.

Unfortunately I think we might have to create a separate rule in Joplin to get it working. Also, I believe the fact that react-native does not allow to use external js, it will have to be injected, thus we might not be able to use a plugin for this at all, but add that code directly to the Joplin project code (in some modified way)....
